module.exports = [
  { route: '/', view: 'index' },
  { route: '/index', redirect: '/' },
  { route: '/cari-properti', view: 'cari-properti' },
  { route: '/cari-agen', view: 'cari-agen' },
  { route: '/agen-detail', view: 'agen-detail' },
  { route: '/properti-detail', view: 'properti-detail' },
  { route: '/kalkulator-kpr', view: 'kalkulator-kpr' },
  { route: '/peta-properti', view: 'peta-properti' },
  { route: '/take-over-kpr', view: 'take-over-kpr' },
  { route: '/tanya-forum', view: 'tanya-forum' },
  { route: '/panduan-beli', view: 'panduan-beli' },
  { route: '/beli-properti-aman', view: 'beli-properti-aman' },
  { route: '/mitra-terpercaya', view: 'mitra-terpercaya' },

  { route: '/agent', view: 'agent/index' },
  { route: '/agent/login', view: 'agent/login' },
  { route: '/agent/dashboard', view: 'agent/dashboard' },
  { route: '/agent/profil', view: 'agent/profil' },
  { route: '/agent/listing-form', view: 'agent/listing-form' },
  { route: '/agent/listing-saya', view: 'agent/listing-saya' },
  { route: '/agent/pesan', view: 'agent/pesan' },

  // Legacy .html routes (backward compatible)
  // { route: '/index.html', view: 'index' },
  // { route: '/cari-properti.html', view: 'cari-properti' },
  // { route: '/cari-agen.html', view: 'cari-agen' },
  // { route: '/agen-detail.html', view: 'agen-detail' },
  // { route: '/properti-detail.html', view: 'properti-detail' },
  // { route: '/kalkulator-kpr.html', view: 'kalkulator-kpr' },
  // { route: '/peta-properti.html', view: 'peta-properti' },
  // { route: '/take-over-kpr.html', view: 'take-over-kpr' },
  // { route: '/tanya-forum.html', view: 'tanya-forum' },
  // { route: '/panduan-beli.html', view: 'panduan-beli' },
  // { route: '/beli-properti-aman.html', view: 'beli-properti-aman' },
  // { route: '/mitra-terpercaya.html', view: 'mitra-terpercaya' },
  // { route: '/agent/index.html', view: 'agent/index' },
  // { route: '/agent/login.html', view: 'agent/login' },
  // { route: '/agent/dashboard.html', view: 'agent/dashboard' },
  // { route: '/agent/profil.html', view: 'agent/profil' },
  // { route: '/agent/listing-form.html', view: 'agent/listing-form' },
  // { route: '/agent/listing-saya.html', view: 'agent/listing-saya' },
  // { route: '/agent/pesan.html', view: 'agent/pesan' },
];
